### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by AmanNegi** [ShimanshuChauhan/ShimanshuChauhan#1]
# Issue
Links provided do not lead anywhere? I would love to follow you, could you please update your social links.

# Supporting Screenshots
- 1: These three links lead nowhere.
![image](https://github.com/ShimanshuChauhan/ShimanshuChauhan/assets/37607224/733ebca9-3185-42d2-85c8-92f0bb7a2f44)

- 2: Not sure if `kakbar` matches your purpose here, also does not lead anywhere.
![image](https://github.com/ShimanshuChauhan/ShimanshuChauhan/assets/37607224/1ee5f44a-b123-45d5-b0a6-9edcabb3ef0d)

**Comment by ShimanshuChauhan** [comment]
Thanks for noticing and sharing the issues ✨

I will surely rectify the same.

**Comment by ShimanshuChauhan** [comment]
# Issue Resolved

- All links are working now and take you to the respective handles

- The `kakbar` logo has been replaced with the `LinkedIn logo`.

<br>

`Earlier`
![earlier-git](https://github.com/ShimanshuChauhan/ShimanshuChauhan/assets/118818189/8b313d17-84ee-4606-996d-1e9e9809ad4a)

`Updated`
![Screenshot (407)](https://github.com/ShimanshuChauhan/ShimanshuChauhan/assets/118818189/99795be1-8d05-489e-8c0a-f1d5a2fd6c31)

**Comment by ShimanshuChauhan** [comment]
Thanks a lot for mentioning the issues
